### ISSUE TITLE
Inserir Registros

### ISSUE THREAD

**Issue by romuloAMR** [romuloAMR/SGBD-ITP#4]
1- Usuário deve informar o nome da tabela
2- Sistema deve solicitar os valores de cada uma das colunas
3- Sistema deve verificar a chave primária
4- Em uma tabela deve existir um e apenas um valor de chave primária. Se o usuário informar uma chave que já existe, sistema deve emitir uma mensagem de erro e não deve inserir o registro

**Comment by Dags0n** [comment]
Para ficar 100% falta apenas considerar o tipo correto de cada coluna.

**Comment by Dags0n** [comment]
Na verdade está com um bug bestinha que eu não tinha percebido, vou consertar.
